package pdftarayici;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.apache.pdfbox.text.PDFTextStripperByArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x.impROS.x
 */
public class pfdAnamenu extends javax.swing.JFrame {

    Timer timer;

    public pfdAnamenu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        tblAra = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBulunanPdfInfo = new javax.swing.JTable();
        pnlAra = new javax.swing.JPanel();
        btnGelismisArama = new javax.swing.JButton();
        txtArananKelime = new javax.swing.JTextField();
        lblArananKelime = new javax.swing.JLabel();
        pnlAyarlar = new javax.swing.JPanel();
        txtArananDizin = new javax.swing.JTextField();
        lblFile = new javax.swing.JLabel();
        pnlListeler = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnListeEkle = new javax.swing.JButton();
        cmbPdfListeleri = new javax.swing.JComboBox();
        lblDurum = new javax.swing.JLabel();
        txtAra = new javax.swing.JTextField();
        btnAra = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAra.setBackground(new java.awt.Color(255, 153, 153));
        tblAra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        tblBulunanPdfInfo.setBackground(new java.awt.Color(204, 255, 204));
        tblBulunanPdfInfo.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        tblBulunanPdfInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dosya Adı", "Başlık", "Yazar", "Konu", "Anahtar Kelimeler", "Oluşturan", "Yapımcı", "Oluşturulma Tarihi", "Düzenleme Tarihi", "Trapped"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBulunanPdfInfo.setCellSelectionEnabled(true);
        tblBulunanPdfInfo.setEditingColumn(0);
        tblBulunanPdfInfo.setEditingRow(0);
        tblBulunanPdfInfo.setFillsViewportHeight(true);
        tblBulunanPdfInfo.setGridColor(new java.awt.Color(0, 0, 0));
        tblBulunanPdfInfo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblBulunanPdfInfo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), tblBulunanPdfInfo, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tblBulunanPdfInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBulunanPdfInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblBulunanPdfInfoMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblBulunanPdfInfo);
        tblBulunanPdfInfo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblBulunanPdfInfo.getColumnModel().getColumnCount() > 0) {
            tblBulunanPdfInfo.getColumnModel().getColumn(0).setResizable(false);
            tblBulunanPdfInfo.getColumnModel().getColumn(1).setResizable(false);
            tblBulunanPdfInfo.getColumnModel().getColumn(2).setResizable(false);
            tblBulunanPdfInfo.getColumnModel().getColumn(3).setResizable(false);
            tblBulunanPdfInfo.getColumnModel().getColumn(4).setResizable(false);
            tblBulunanPdfInfo.getColumnModel().getColumn(5).setResizable(false);
            tblBulunanPdfInfo.getColumnModel().getColumn(6).setResizable(false);
            tblBulunanPdfInfo.getColumnModel().getColumn(7).setResizable(false);
            tblBulunanPdfInfo.getColumnModel().getColumn(8).setResizable(false);
        }

        tblAra.addTab("Ana Menü", jScrollPane2);

        pnlAra.setBackground(new java.awt.Color(204, 255, 204));

        btnGelismisArama.setText("Ara");
        btnGelismisArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGelismisAramaActionPerformed(evt);
            }
        });

        lblArananKelime.setText("Aranacak Kelime :");

        javax.swing.GroupLayout pnlAraLayout = new javax.swing.GroupLayout(pnlAra);
        pnlAra.setLayout(pnlAraLayout);
        pnlAraLayout.setHorizontalGroup(
            pnlAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAraLayout.createSequentialGroup()
                .addGroup(pnlAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAraLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblArananKelime)
                        .addGap(10, 10, 10)
                        .addComponent(txtArananKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAraLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnGelismisArama, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(931, 931, 931))
        );
        pnlAraLayout.setVerticalGroup(
            pnlAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAraLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAraLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblArananKelime))
                    .addComponent(txtArananKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnGelismisArama))
        );

        tblAra.addTab("Gelişmiş Arama", pnlAra);

        pnlAyarlar.setBackground(new java.awt.Color(204, 255, 204));
        pnlAyarlar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArananDizin.setText("E:\\Pdfler2");
        pnlAyarlar.add(txtArananDizin, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 11, 320, -1));

        lblFile.setText("Arama Dizini : ");
        pnlAyarlar.add(lblFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 14, -1, -1));

        tblAra.addTab("Ayarlar", pnlAyarlar);

        javax.swing.GroupLayout pnlListelerLayout = new javax.swing.GroupLayout(pnlListeler);
        pnlListeler.setLayout(pnlListelerLayout);
        pnlListelerLayout.setHorizontalGroup(
            pnlListelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1218, Short.MAX_VALUE)
        );
        pnlListelerLayout.setVerticalGroup(
            pnlListelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        tblAra.addTab("Listelerim", pnlListeler);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1218, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        tblAra.addTab("Son Kullanılanlar", jPanel2);

        getContentPane().add(tblAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        btnListeEkle.setText("Listeye Ekle");
        getContentPane().add(btnListeEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 11, -1, -1));

        cmbPdfListeleri.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbPdfListeleri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 193, -1));

        lblDurum.setText("Hazır");
        getContentPane().add(lblDurum, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 15, -1, -1));

        txtAra.setBackground(new java.awt.Color(153, 255, 255));
        txtAra.setBorder(null);
        txtAra.setDisabledTextColor(new java.awt.Color(255, 153, 153));
        txtAra.setOpaque(false);
        getContentPane().add(txtAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 120, 20));

        btnAra.setText("Ara");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });
        getContentPane().add(btnAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1184, 11, -1, -1));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 11, 184, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/txtAra.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 134, -1));

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblBulunanPdfInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBulunanPdfInfoMouseEntered

    }//GEN-LAST:event_tblBulunanPdfInfoMouseEntered

    private void tblBulunanPdfInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBulunanPdfInfoMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblBulunanPdfInfo.getModel();

        System.out.println("Tek Click" + model.getValueAt(tblBulunanPdfInfo.getSelectedRow(), tblBulunanPdfInfo.getSelectedColumn()));
        pdfAc(txtArananDizin.getText() + "\\" + model.getValueAt(0, tblBulunanPdfInfo.getSelectedColumn()));
    }//GEN-LAST:event_tblBulunanPdfInfoMouseClicked

    private void btnGelismisAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGelismisAramaActionPerformed
        // PDF ara ve listboxa ekle
        tblAra.setSelectedIndex(0);

        lblDurum.setText("Hedef Dizin Taranıyor..");
        PdfTaraClass pdfTara2  =new PdfTaraClass(txtArananDizin.getText());
        pdfTara2.start();
       // aramaPdf();
       // bilgiYerlestir();

    }//GEN-LAST:event_btnGelismisAramaActionPerformed

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAraActionPerformed
    int sayac = 0;

    private void aramaPdf() {
        System.out.println("Girildi Arama Pdf");
        TimerTask tasknew = new TimerTask() {
            ArrayList<File> arrpdfBulunan;

            @Override
            public void run() {
      
            }

        };
        timer = new Timer();

        timer.schedule(tasknew, 100, 1000);
    }

    private void bilgiYerlestir(ArrayList<String> arrPdfBilgileri) {
        System.out.println("Girildi Bilgi Yerleştir");
        DefaultTableModel model = (DefaultTableModel) tblBulunanPdfInfo.getModel();

        String[] arrPdfInfo = new String[10];
        for (int i = 0; i < 10; i++) {
            arrPdfInfo[i] = arrPdfBilgileri.get(i);
            System.out.println("Bilgi Yerleştiriliyor " + i);
        }
        System.out.println("Arr = " + Arrays.toString(arrPdfInfo));
        model.addRow(arrPdfInfo);
        System.out.println("Bilgi Yerleştirden Çıkılıyor");
    }

 

    void pdfAc(String strPdf) {
        try {
            Desktop.getDesktop().open(new File(strPdf));
            System.out.println("2.Yontem Basariyla Tamamlandi");
        } catch (IOException ex) {
            System.out.println("Hata : " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pfdAnamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pfdAnamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pfdAnamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pfdAnamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new pfdAnamenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnGelismisArama;
    private javax.swing.JButton btnListeEkle;
    private javax.swing.JComboBox cmbPdfListeleri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArananKelime;
    private javax.swing.JLabel lblDurum;
    private javax.swing.JLabel lblFile;
    private javax.swing.JPanel pnlAra;
    private javax.swing.JPanel pnlAyarlar;
    private javax.swing.JPanel pnlListeler;
    private javax.swing.JTabbedPane tblAra;
    private javax.swing.JTable tblBulunanPdfInfo;
    private javax.swing.JTextField txtAra;
    private javax.swing.JTextField txtArananDizin;
    public static javax.swing.JTextField txtArananKelime;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
