/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agacdeneme;

import java.io.*;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author x.impROS.x
 */
public class AgacTest extends javax.swing.JFrame {

    /**
     * Creates new form AgacTest
     */
    public AgacTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdSoyad = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNumara = new javax.swing.JTextPane();
        lblAdSoyad = new javax.swing.JLabel();
        lblNumara = new javax.swing.JLabel();
        lblDurum = new javax.swing.JLabel();
        btnAra = new javax.swing.JButton();
        btnEkle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAdSoyad.setText("impROS");
        jScrollPane1.setViewportView(txtAdSoyad);

        jScrollPane2.setViewportView(txtNumara);

        lblAdSoyad.setText("Ad Soyad :");

        lblNumara.setText("Numara :");

        lblDurum.setText("Hazır");

        btnAra.setText("Ara");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdSoyad)
                            .addComponent(lblNumara))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDurum)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblDurum)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdSoyad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAra)
                    .addComponent(btnEkle))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
        isimSorgula(txtAdSoyad.getText());
    }//GEN-LAST:event_btnAraActionPerformed

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        try {
            kartvizitEkle(txtAdSoyad.getText(), txtNumara.getText());
        } catch (IOException ex) {
            hata(ex);
        }
    }//GEN-LAST:event_btnEkleActionPerformed
    private void hata(Exception ex) {
        lblDurum.setText(ex.getMessage());
    }

    private void numaraYaz(File dosya, String strNumara) throws IOException {
        FileWriter dosyaYazici = null;
        BufferedWriter tamponYazici = null;
        try {
            dosyaYazici = new FileWriter(dosya);
            tamponYazici = new BufferedWriter(dosyaYazici);
            tamponYazici.write(strNumara);
            System.out.println("Numara Yazildi");
        } catch (IOException ex) {
            lblDurum.setText("Numara Yazilamadi");
        } finally {
            tamponYazici.close();
            dosyaYazici.close();
        }
    }

    private String isimSorgula(String strAdSoyad) {
        File dosyaKartvizit;
        File dosyaNumara;
        String strTempDosya = "C:\\Users\\x.impROS.x\\Documents\\NetBeansProjects\\AgacDeneme\\data\\";

        for (int i = 0; i < strAdSoyad.length(); i++) {
            strTempDosya += "\\" + strAdSoyad.charAt(i) + "\\";
        }
        dosyaKartvizit = new File(strTempDosya);
        dosyaNumara = new File(dosyaKartvizit.getAbsolutePath() + "//numara.txt");
        strTempDosya = strTempDosya.replace(" ", "");
        if (dosyaNumara.exists()) {
            txtNumara.setText(okuText(dosyaNumara));
        } else {
            lblDurum.setText("Kayit Bulunamadi");
            txtNumara.setText("");
        }
        return strTempDosya;
    }

    private String okuText(File dosya) {
        String strOkunan = "", strVeri = "";
        try {
            FileReader dosyaOkuyucu = new FileReader(dosya);
            BufferedReader tamponOkuyucu = new BufferedReader(dosyaOkuyucu);

            while ((strOkunan = tamponOkuyucu.readLine()) != null) {
                strVeri += strOkunan;
            }
        } catch (IOException ex) {
            hata(ex);
        }
        return strVeri;
    }

    private void kartvizitEkle(String strAdSoyad, String strNumara) throws IOException {
        File dosyaKartvizit;
        File dosyaNumara;
        String strTempDosya = "C:\\Users\\x.impROS.x\\Documents\\NetBeansProjects\\AgacDeneme\\data\\";

        for (int i = 0; i < strAdSoyad.length(); i++) {
            strTempDosya += "\\" + strAdSoyad.charAt(i) + "\\";
        }
        strTempDosya = strTempDosya.replace(" ", "");
        System.out.println("Olusturulacak Dosya**** : " + strTempDosya);

        dosyaKartvizit = new File(strTempDosya);
        dosyaNumara = new File(dosyaKartvizit.getAbsolutePath() + "//numara.txt");
        if (!dosyaNumara.exists()) {
            boolean mkdirs = dosyaKartvizit.mkdirs();

            numaraYaz(dosyaNumara, strNumara);
        } else {
            lblDurum.setText("Dosya Olusturulamadi veya Zaten Var.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgacTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgacTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgacTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgacTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgacTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnEkle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdSoyad;
    private javax.swing.JLabel lblDurum;
    private javax.swing.JLabel lblNumara;
    private javax.swing.JTextPane txtAdSoyad;
    private javax.swing.JTextPane txtNumara;
    // End of variables declaration//GEN-END:variables
}
