/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package picsmallerv1;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author x.impROS.x
 */
public class picSmaller_anamenu extends javax.swing.JFrame {

    /**
     * Creates new form picSmaller_anamenu
     */
    public picSmaller_anamenu() {
        initComponents();
        txtKalite.setBackground(new Color(0, 0, 0, 0));
        txtProgressValue.setBackground(new Color(0, 0, 0, 0));
        txtDizin.setBackground(new Color(0, 0, 0, 0));
        txtLogoOpaklık.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBasla = new javax.swing.JLabel();
        lblProgressbar = new javax.swing.JLabel();
        txtDizin = new javax.swing.JTextField();
        txtProgressValue = new javax.swing.JTextField();
        txtKalite = new javax.swing.JTextField();
        txtLogoOpaklık = new javax.swing.JTextField();
        lblResimSec = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHakkında_Hover = new javax.swing.JLabel();
        lblAyarlar_Hover = new javax.swing.JLabel();
        lblTopluKlasor_Hover = new javax.swing.JLabel();
        lblPng_Hover = new javax.swing.JLabel();
        lblJpg_Hover = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblArkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBasla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBaslaMouseClicked(evt);
            }
        });
        getContentPane().add(lblBasla, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 474, 70, 30));

        lblProgressbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/progress_Wait.png"))); // NOI18N
        getContentPane().add(lblProgressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 479, 310, 40));

        txtDizin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDizin.setForeground(new java.awt.Color(255, 255, 255));
        txtDizin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDizin.setText("Secili Resim Yok");
        txtDizin.setAutoscrolls(false);
        txtDizin.setBorder(null);
        txtDizin.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        txtDizin.setEnabled(false);
        txtDizin.setOpaque(false);
        txtDizin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDizinActionPerformed(evt);
            }
        });
        getContentPane().add(txtDizin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 310, 20));

        txtProgressValue.setEditable(false);
        txtProgressValue.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        txtProgressValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProgressValue.setText("%0");
        txtProgressValue.setBorder(null);
        txtProgressValue.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        txtProgressValue.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProgressValue.setEnabled(false);
        txtProgressValue.setOpaque(false);
        getContentPane().add(txtProgressValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 460, 30, 20));

        txtKalite.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtKalite.setForeground(new java.awt.Color(255, 255, 255));
        txtKalite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKalite.setText("50");
        txtKalite.setAutoscrolls(false);
        txtKalite.setBorder(null);
        txtKalite.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        txtKalite.setOpaque(false);
        txtKalite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKaliteActionPerformed(evt);
            }
        });
        getContentPane().add(txtKalite, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 80, 20));

        txtLogoOpaklık.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLogoOpaklık.setForeground(new java.awt.Color(255, 255, 255));
        txtLogoOpaklık.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLogoOpaklık.setText("Sağ Alt");
        txtLogoOpaklık.setBorder(null);
        txtLogoOpaklık.setOpaque(false);
        getContentPane().add(txtLogoOpaklık, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 365, 80, 20));

        lblResimSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/sec.png"))); // NOI18N
        getContentPane().add(lblResimSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 134, 420, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("50");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 70, 20));

        lblHakkında_Hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHakkında_HoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHakkında_HoverMouseExited(evt);
            }
        });
        getContentPane().add(lblHakkında_Hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, 30));

        lblAyarlar_Hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAyarlar_HoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAyarlar_HoverMouseExited(evt);
            }
        });
        getContentPane().add(lblAyarlar_Hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 70, 30));

        lblTopluKlasor_Hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTopluKlasor_HoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTopluKlasor_HoverMouseExited(evt);
            }
        });
        getContentPane().add(lblTopluKlasor_Hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 70, 30));

        lblPng_Hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPng_HoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPng_HoverMouseExited(evt);
            }
        });
        getContentPane().add(lblPng_Hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 70, 30));

        lblJpg_Hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJpg_HoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJpg_HoverMouseExited(evt);
            }
        });
        getContentPane().add(lblJpg_Hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 70, 30));

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/menuSade.png"))); // NOI18N
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 410, 50));

        lblArkaplan.setForeground(new java.awt.Color(255, 255, 255));
        lblArkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/arkaplan5.png"))); // NOI18N
        getContentPane().add(lblArkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblJpg_HoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJpg_HoverMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/jpg_Hover.png"))); // NOI18N
    }//GEN-LAST:event_lblJpg_HoverMouseEntered

    private void lblJpg_HoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJpg_HoverMouseExited
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/menuSade.png")));
    }//GEN-LAST:event_lblJpg_HoverMouseExited

    private void lblPng_HoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPng_HoverMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/png_Hover.png")));
    }//GEN-LAST:event_lblPng_HoverMouseEntered

    private void lblPng_HoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPng_HoverMouseExited
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/menuSade.png")));
    }//GEN-LAST:event_lblPng_HoverMouseExited

    private void lblTopluKlasor_HoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTopluKlasor_HoverMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/topluKlasor_Hover.png")));
    }//GEN-LAST:event_lblTopluKlasor_HoverMouseEntered

    private void lblTopluKlasor_HoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTopluKlasor_HoverMouseExited
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/menuSade.png")));
    }//GEN-LAST:event_lblTopluKlasor_HoverMouseExited

    private void lblAyarlar_HoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAyarlar_HoverMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/ayarlar_Hover.png")));
    }//GEN-LAST:event_lblAyarlar_HoverMouseEntered

    private void lblAyarlar_HoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAyarlar_HoverMouseExited
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/menuSade.png")));
    }//GEN-LAST:event_lblAyarlar_HoverMouseExited

    private void lblHakkında_HoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHakkında_HoverMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/hakkinda_Hover.png")));
    }//GEN-LAST:event_lblHakkında_HoverMouseEntered

    private void lblHakkında_HoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHakkında_HoverMouseExited
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/menuSade.png")));
    }//GEN-LAST:event_lblHakkında_HoverMouseExited

    private void txtKaliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKaliteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKaliteActionPerformed

    private void txtDizinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDizinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDizinActionPerformed

    private void lblBaslaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBaslaMouseClicked
       lblProgressbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/progressbar1.gif")));
    }//GEN-LAST:event_lblBaslaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(picSmaller_anamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(picSmaller_anamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(picSmaller_anamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(picSmaller_anamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new picSmaller_anamenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblArkaplan;
    private javax.swing.JLabel lblAyarlar_Hover;
    private javax.swing.JLabel lblBasla;
    private javax.swing.JLabel lblHakkında_Hover;
    private javax.swing.JLabel lblJpg_Hover;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblPng_Hover;
    private javax.swing.JLabel lblProgressbar;
    private javax.swing.JLabel lblResimSec;
    private javax.swing.JLabel lblTopluKlasor_Hover;
    private javax.swing.JTextField txtDizin;
    private javax.swing.JTextField txtKalite;
    private javax.swing.JTextField txtLogoOpaklık;
    private javax.swing.JTextField txtProgressValue;
    // End of variables declaration//GEN-END:variables
}
