
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x.impROS.x
 */
public class gif extends javax.swing.JFrame {

  //  Icon loading = new ImageIcon(getClass().getResource("001.gif"));

    public gif() {
        initComponents();
        // jLabel1.add(" loading", loading, JLabel.CENTER);
        Icon loading = new ImageIcon(getClass().getResource("001.gif"));
        JLabel jLabel1 = new JLabel("  loading ", loading, JLabel.CENTER);
        jLabel1.setBounds(100, 50, 100, 100);
        add(jLabel1);
        
        loading = new ImageIcon(getClass().getResource("002.gif"));
        JLabel jLabel2 = new JLabel("  loading ", loading, JLabel.CENTER);
       jLabel2.setBounds(200, 50, 100, 100);
        add(jLabel2);
        
        loading = new ImageIcon(getClass().getResource("003.gif"));
        JLabel jLabel3 = new JLabel("  loading ", loading, JLabel.CENTER);
        jLabel3.setBounds(100, 100, 100, 100);
        add(jLabel3);
//        
        loading = new ImageIcon(getClass().getResource("004.gif"));
        JLabel jLabel4 = new JLabel("  loading ", loading, JLabel.CENTER);
        jLabel4.setBounds(100, 200, 100, 100);
        add(jLabel4);
//        
        loading = new ImageIcon(getClass().getResource("005.gif"));
        JLabel jLabel5 = new JLabel("  loading ", loading, JLabel.CENTER);
        jLabel5.setBounds(100, 300, 100, 100);
        add(jLabel5);
        
         loading = new ImageIcon(getClass().getResource("006.gif"));
        JLabel jLabel6= new JLabel("  loading ", loading, JLabel.CENTER);
        jLabel6.setBounds(200, 300, 100, 100);
        add(jLabel6);
        
          loading = new ImageIcon(getClass().getResource("007.gif"));
        JLabel jLabel7= new JLabel("  loading ", loading, JLabel.CENTER);
        jLabel7.setBounds(300, 300, 100, 100);
        add(jLabel7);
        
        loading = new ImageIcon(getClass().getResource("008.gif"));
        JLabel jLabel8= new JLabel("  loading ", loading, JLabel.CENTER);
        jLabel8.setBounds(300, 500, 100, 100);
        add(jLabel8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/002.gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new gif().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
