/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resimboyutdegistirmepro;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author x.impROS.x
 */
public class PicSizeAnamenu extends javax.swing.JFrame {

    String imgfolder = System.getProperty("user.dir") + "\\img\\";
    JFileChooser fc = new JFileChooser(imgfolder);
    DefaultListModel listModel = new DefaultListModel();
    Date zaman = new Date();
    int baslangicZaman = 0, bitisZaman = 0, gecenSure = 0;
    int baslangicSaat = 0, baslangicDakika = 0, baslangicSaniye = 0;

    /**
     * Creates new form PicSizeAnamenu
     */
    public PicSizeAnamenu() {
        initComponents();
        fc.setDialogTitle("Resim Klasörü SeÇ");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setAcceptAllFileFilterUsed(false);
        lstResimler.setModel(listModel);

        jProgressBar1.setStringPainted(true);

        this.getContentPane().setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThreadCalis = new javax.swing.JButton();
        spnKalite = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDizin = new javax.swing.JTextField();
        btnDizinSec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResimler = new javax.swing.JList();
        lblDurum = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKaydet = new javax.swing.JTextPane();
        btnKaydet = new javax.swing.JButton();
        lbKaydet = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLogo = new javax.swing.JTextPane();
        btnLogoSec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnThreadCalis.setText("Başla");
        btnThreadCalis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreadCalisActionPerformed(evt);
            }
        });

        spnKalite.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        spnKalite.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(5.0f), Float.valueOf(0.0f), Float.valueOf(10.0f), Float.valueOf(1.0f)));
        spnKalite.setName(""); // NOI18N

        jLabel1.setText("Resim Kalitesi : ");

        jLabel2.setText("Resim Dizini :");

        txtDizin.setText("E:\\Ekran Goruntuleri");
        txtDizin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDizinActionPerformed(evt);
            }
        });

        btnDizinSec.setText("Sec");
        btnDizinSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDizinSecActionPerformed(evt);
            }
        });

        lstResimler.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstResimler);

        lblDurum.setText("Hazır");

        jProgressBar1.setStringPainted(true);

        jScrollPane2.setViewportView(txtKaydet);

        btnKaydet.setText("Sec");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        lbKaydet.setText("Kaydet :");

        lblLogo.setText("Logo :");

        txtLogo.setAutoscrolls(false);
        jScrollPane3.setViewportView(txtLogo);

        btnLogoSec.setText("Sec");
        btnLogoSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoSecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(spnKalite, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThreadCalis, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(130, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDurum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblLogo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLogoSec))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDizin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDizinSec))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbKaydet)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKaydet)))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDurum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThreadCalis)
                    .addComponent(spnKalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKaydet, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbKaydet)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogoSec, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLogo)
                                .addGap(8, 8, 8))))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDizin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnDizinSec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private int zamanToSaniye(int saat, int dakika, int saniye) {
        System.out.println(saat + " Saat," + dakika + " Dakika," + saniye + " Saniye.");
        saniye = (saat * 3600) + (dakika * 60) + saniye;
        return saniye;
    }

    private String saniyeHesapla() {
        int gecenSaat = zaman.getHours() - baslangicSaat;
        System.out.println("Gecen Saat : " + gecenSaat);
        int gecenDakika = zaman.getMinutes() - baslangicDakika;
        System.out.println("Gecen Dakika : " + gecenDakika);
        int gecenSaniye = zaman.getSeconds() - baslangicSaniye;
        int gecenSure = (gecenSaat * 3600) + (gecenDakika * 60) + gecenSaniye;
        System.out.println("GecenSaniye :" + gecenSure);
        return gecenSaat + " Saat," + gecenDakika + " Dakika," + gecenSaniye + " Saniye.";
    }

    private String saniyeToZaman(int saniye) {
        int saat = saniye / 3600;
        saniye = saniye % 3600;
        int dakika = saniye / 60;
        saniye = saniye % 60;
        return saat + " Saat," + dakika + " Dakika," + saniye + " Saniye.";
    }
    private void btnDizinSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDizinSecActionPerformed
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            String dizin = fc.getSelectedFile() + "";
            txtDizin.setText(dizin);

        }
        File resimDizin = new File(txtDizin.getText());
        arrResimler.clear();
        listModel.clear();
        listele(resimDizin);
    }//GEN-LAST:event_btnDizinSecActionPerformed

    Timer timer;
    TimerTask tasknew;
    static String strGecenZaman;

    private void progressBarKontrol() {

        tasknew = new TimerTask() {

            @Override
            public void run() {
                //System.out.println("timer working");
                jProgressBar1.setValue((int) ResimKucultmeClass.progressBarValue);;
                TitledBorder border = BorderFactory.createTitledBorder("işlemler yapılıyor..");
                jProgressBar1.setBorder(border);
                if (ResimKucultmeClass.progressBarValue >= 100) {

                    zaman = new Date();
                    bitisZaman = zamanToSaniye(zaman.getHours(), zaman.getMinutes(), zaman.getSeconds());

                    //   System.out.println("Gece Sure : " + saniyeHesapla());
                    lblDurum.setText("İşlem Başarıyla Tamamlandı.Geçen Süre : " + strGecenZaman);
                    listModel.clear();
                    arrResimler.clear();
                    btnThreadCalis.setText("Başlat");
                    ResimKucultmeClass.progressBarValue = 0;
                    border = BorderFactory.createTitledBorder("Tüm İşlemler Başarıyla Tamamlandı.");
                    jProgressBar1.setBorder(border);

                    sayac = 2;
                    timer.cancel();
                }
            }
        };
        timer = new Timer();

        timer.schedule(tasknew, 100, 1000);
    }
    int sayac = 0;
    private void btnThreadCalisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreadCalisActionPerformed
        float kalite = (float) spnKalite.getValue();
        System.out.println("Kalite : " + kalite);
        ResimKucultmeClass resimKucult = new ResimKucultmeClass(arrResimler, kalite);
        if (sayac % 2 == 0) {
            if (arrResimler.size() <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Lütfen Bir veya Daha Fazla Dosya Seçiniz", "Resim Yok", WIDTH);
            } else {

                baslangicSaat = zaman.getHours();
                baslangicDakika = zaman.getMinutes();
                baslangicSaniye = zaman.getSeconds();
                sayac++;
                btnThreadCalis.setText("Durdur");
                resimKucult.start();
                lblDurum.setText("Resimler Kucultuluyor");
                progressBarKontrol();
            }
        } else {
            sayac++;
            jProgressBar1.setValue(0);
            ResimKucultmeClass.progressBarValue = 0;
            lblDurum.setText("İşlem  Yarıda Kesildi.Geçen Süre : " + saniyeToZaman(gecenSure));
            listModel.clear();
            arrResimler.clear();
            timer.cancel();
            resimKucult.stop();
            btnThreadCalis.setText("Başlat");;
        }


    }//GEN-LAST:event_btnThreadCalisActionPerformed

    private void txtDizinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDizinActionPerformed

    }//GEN-LAST:event_txtDizinActionPerformed
    static String resimKaydetDizin;
    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            String dizin = fc.getSelectedFile() + "";
            txtKaydet.setText(dizin);
            resimKaydetDizin = dizin;
        }


    }//GEN-LAST:event_btnKaydetActionPerformed
    static File logo;
    private void btnLogoSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoSecActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF Images", "jpg", "png");
        chooser.setFileFilter(filter);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            logo = chooser.getSelectedFile();
            txtLogo.setText(logo.getAbsolutePath());

        }
    }//GEN-LAST:event_btnLogoSecActionPerformed

    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PicSizeAnamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PicSizeAnamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PicSizeAnamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PicSizeAnamenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PicSizeAnamenu().setVisible(true);
            }
        });
    }
    static File[] klasoricindekiler;
    static ArrayList<File> arrResimler = new ArrayList<>();
    ArrayList<File> arrThread1, arrThread2;

    private void listele(File klasor) {

        try {
            File[] arrklasoricindekiler = klasor.listFiles();
            for (File klasoricindekiler1 : arrklasoricindekiler) {
                if (klasoricindekiler1.isDirectory()) {

                    listele(klasoricindekiler1);
                } else {
                    if (klasoricindekiler1.getName().toLowerCase().endsWith(".png") || klasoricindekiler1.getName().toLowerCase().endsWith(".jpg")) {
                        arrResimler.add(klasoricindekiler1);

                        listModel.addElement(klasoricindekiler1);
                    }
                }
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    int yuzdelik = 0;

//<editor-fold defaultstate="collapsed" desc="Componentler">

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDizinSec;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnLogoSec;
    private javax.swing.JButton btnThreadCalis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbKaydet;
    private javax.swing.JLabel lblDurum;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JList lstResimler;
    private javax.swing.JSpinner spnKalite;
    private javax.swing.JTextField txtDizin;
    private javax.swing.JTextPane txtKaydet;
    private javax.swing.JTextPane txtLogo;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
