/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online_ceviri;

/**
 *
 * @author x.impROS.x
 */
public class AnaMenu extends javax.swing.JFrame {

    /**
     * Creates new form AnaMenu
     */
    public AnaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKelime = new javax.swing.JTextField();
        lblKelime = new javax.swing.JLabel();
        btnCevir = new javax.swing.JButton();
        cmbKaynak = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCevrilen = new javax.swing.JTextArea();
        cmdHedef = new javax.swing.JComboBox();
        lblKaynak = new javax.swing.JLabel();
        lblHedef = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtKelime.setToolTipText("Bir Kelime Giriniz");

        lblKelime.setText("Kelime :");

        btnCevir.setText("Çevir");
        btnCevir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCevirActionPerformed(evt);
            }
        });

        cmbKaynak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingilizce", "Türkçe" }));

        txtCevrilen.setColumns(20);
        txtCevrilen.setRows(5);
        jScrollPane1.setViewportView(txtCevrilen);

        cmdHedef.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Türkçe", "Ingilizce" }));

        lblKaynak.setText("Kaynak Dil");

        lblHedef.setText("Hedef Dil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbKaynak, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKaynak))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHedef)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCevir)
                                    .addComponent(cmdHedef, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKelime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKaynak)
                    .addComponent(lblHedef))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKaynak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdHedef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKelime)
                    .addComponent(btnCevir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCevirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCevirActionPerformed
        cevirmeClass translate = new cevirmeClass();
        System.out.println("getSelectedItem " + cmbKaynak.getSelectedItem());
        System.out.println("getSelectedIndex()" + cmbKaynak.getSelectedIndex());
        if (cmbKaynak.getSelectedItem().equals("Türkçe") && cmdHedef.getSelectedItem().equals("Ingilizce")) {
            txtCevrilen.setText(translate.cevir(txtKelime.getText(), cevirmeClass.DocumentType.Turkce, cevirmeClass.DocumentType.Ingilizce));
            System.out.println("Turkce To Ingilizce");
        } else if (cmbKaynak.getSelectedItem().equals("Ingilizce") && cmdHedef.getSelectedItem().equals("Türkçe")) {
            txtCevrilen.setText(translate.cevir(txtKelime.getText(), cevirmeClass.DocumentType.Ingilizce, cevirmeClass.DocumentType.Turkce));
            System.out.println("Ingilizce to Turkce");
        }
//https://tr.wiktionary.org/wiki/Vikis%C3%B6zl%C3%BCk:S%C3%B6zc%C3%BCk_listesi
    }//GEN-LAST:event_btnCevirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCevir;
    private javax.swing.JComboBox cmbKaynak;
    private javax.swing.JComboBox cmdHedef;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHedef;
    private javax.swing.JLabel lblKaynak;
    private javax.swing.JLabel lblKelime;
    private javax.swing.JTextArea txtCevrilen;
    private javax.swing.JTextField txtKelime;
    // End of variables declaration//GEN-END:variables
}
